### ISSUE TITLE
Remaining components/ tools

### ISSUE THREAD

**Issue by mikeshams** [nireehasharma/Capstone-Project_G3#3]
Show me the rest of your components/ tools as soon as you receive them:
	Raspberry pi 4 model B Board
	NEMA 17 stepper motor
	Stepper Driver (DRV8825) 
        HD44780 series LCD Display (20*4) 
	PIR Motion Sensor
	Raspberry pi Camera V2 – 8MP
	Breadboard and Jumper wires
	Soldering tools and DMM

**Comment by SumanMosam** [comment]
Sir, as soon as we receive the remaining components we can show the components in the class.

**Comment by SumanMosam** [comment]
Sir we got these components in recent days
Soldering tools and DMM, Raspberry pi 4 model B Board, PIR Motion Sensor
Raspberry pi Camera V2 – 8MP

**Comment by mikeshams** [comment]
So the remaining components to display include:
NEMA 17 stepper motor
Stepper Driver (DRV8825)
HD44780 series LCD Display (20*4)

**Comment by SumanMosam** [comment]
Sir we got the stepper motors yesterday so we can show the components in the class

**Comment by mikeshams** [comment]
So the remaining components to display include:
Stepper Driver (DRV8825)
HD44780 series LCD Display (20*4)

**Comment by SumanMosam** [comment]
Sir the HD44780 series LCD display is expected to arrive tomorrow.

**Comment by SumanMosam** [comment]
Sir, the LCD display is delayed by the courier service, and we are sorry for that, and I'll notice you for further updates.

**Comment by SumanMosam** [comment]
Sir we got the LCD display and we can show in the class

**Comment by mikeshams** [comment]
So the stepper driver is remaining to arrive.

**Comment by mikeshams** [comment]
keep me posted!

**Comment by SumanMosam** [comment]
The remaining component stepper driver is delivered today sir.
