### ISSUE TITLE
Your PPT file

### ISSUE THREAD

**Issue by mikeshams** [nireehasharma/Capstone-Project_G3#4]
Modify the references based on APA STYLE

**Comment by SumanMosam** [comment]
[First Individual Meeting_Suman Mosam (2) (1).pptx](https://github.com/nireehasharma/Capstone-Project_G3/files/6611972/First.Individual.Meeting_Suman.Mosam.2.1.pptx)
Sir, we changed the references to the APA atyle

**Comment by SumanMosam** [comment]
[First Individual Meeting_Suman Mosam (2).pptx](https://github.com/nireehasharma/Capstone-Project_G3/files/6611980/First.Individual.Meeting_Suman.Mosam.2.pptx)
This is the full PPT file sir
