### ISSUE TITLE
Testing Components

### ISSUE THREAD

**Issue by mikeshams** [nireehasharma/Capstone-Project_G3#5]
1. Please modify your references to have more and also in APA style!
2. Demonstrate the remaining components when receive:
NEMA 17 stepper motor
Stepper Driver (DRV8825) 
HD44780 series LCD Display (20*4) 
Raspberry pi Camera V2 – 8MP

**Comment by Srisatya912** [comment]
sir, I have changed my references to APA style and added more references to ppt. I have tested PIR sensor with the help of LED to detect motion and I have updated a new file. I will demonstrate remaining components testing once we receive them. Below is the attachment of updated ppt file. Thank you.

[Testing Componets_First Individual Meeting (1).pptx](https://github.com/nireehasharma/Capstone-Project_G3/files/6651289/Testing.Componets_First.Individual.Meeting.1.pptx)

**Comment by mikeshams** [comment]
So just demonstrate the remaining components when receive:
NEMA 17 stepper motor
Stepper Driver (DRV8825)
HD44780 series LCD Display (20*4)
Raspberry pi Camera V2 – 8MP

**Comment by Srisatya912** [comment]
Sir, we received stepper motors but not stepper driver. So I can’t test stepper motor now. Remaining components are yet to come. I will update again when we receive them and testing is done. Thank you.

**Comment by mikeshams** [comment]
So just demonstrate the remaining components when receive:
Stepper Driver (DRV8825)
HD44780 series LCD Display (20*4)
Raspberry pi Camera V2 – 8MP

**Comment by Srisatya912** [comment]
Sir, we didn’t received all the components. I will update it again and demonstrate when we receive all the components. Thank you.

**Comment by Srisatya912** [comment]
Hi sir. We didn’t received all the components. May be we will get them by tomorrow night. So, when we receive all the components, I will test them and update it to you. Thank you.

**Comment by Srisatya912** [comment]
sir. I have tested raspberry pi camera and I'm ready top demonstrate it. Below is the attached file about the steps to test raspberry pi camera. Thank you.
[Testing pi camera.docx](https://github.com/nireehasharma/Capstone-Project_G3/files/6706072/Testing.pi.camera.docx)

**Comment by mikeshams** [comment]
So stepper drivers nd LCD display are left!

**Comment by Srisatya912** [comment]
Hi sir. We still haven’t received stepper drivers and LCD. I will update when we receive them. Thank you.

**Comment by Srisatya912** [comment]
Hi sir. LCD and stepper driver got delayed for delivery. I will update and test them when we receive them. Thank you.

**Comment by Srisatya912** [comment]
Hi sir. We received lcd and I tested it. I’m ready to test it but nishitha is absent today.she have all the components so I will show and test on Wednesday. Thank you sir.

**Comment by Srisatya912** [comment]
[Testing LCD with Arduino.docx](https://github.com/nireehasharma/Capstone-Project_G3/files/6778913/Testing.LCD.with.Arduino.docx)
Hir sir. I can explain LCD testing today. We still didn’t received stepper driver, I will update it again when we will receive them.

**Comment by mikeshams** [comment]
well noted

**Comment by Srisatya912** [comment]
Hi sir. We still haven’t received stepper driver. I will update again when we received it and testing is done . Thank you.

**Comment by Srisatya912** [comment]
We still didn’t received stepper driver sir.

**Comment by Srisatya912** [comment]
We still didn’t received stepper driver sir. I will update it when we receive it. Thank you.

**Comment by Srisatya912** [comment]
Hi sir. we received stepper driver and give me sometime to test it sir. once my testing is done I will update it. thank you.

**Comment by Srisatya912** [comment]
https://lastminuteengineers.com/drv8825-stepper-motor-driver-arduino-tutorial/
Hi sir, I have tested stepper motor and driver according to the above link but the motor is not activated. There might be issue with soldering or connecting wires. please give me some time to fix this issue sir. Thank you.

**Comment by Srisatya912** [comment]
Hi sir. I have to do few modifications to the circuit. I will update and do it by wednesday. Thank you.

**Comment by Srisatya912** [comment]
hi sir. Testing stepper motor and stepper driver with arduino is done. I'm ready to demonstrate. below is the file regarding testing. Thank you.
[Stepper test modified.docx](https://github.com/nireehasharma/Capstone-Project_G3/files/6893323/Stepper.test.modified.docx)
