### ISSUE TITLE
PIR Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [nireehasharma/Capstone-Project_G3#7]
How to make the sensor results more stable?

**Comment by Srisatya912** [comment]
I’m working on it sir. When I got an answer I will update it you. Thank you.

**Comment by Srisatya912** [comment]
Please give me some time sir. I will update it by Monday. Thank you.

**Comment by Srisatya912** [comment]
To make PIR motion sensor more stable we used LED which blinks ON when motion is detected and OFF when motion is not detected. Below is the attached file of motion detection of PIR sensor stable.
[PIR_github issue.docx](https://github.com/nireehasharma/Capstone-Project_G3/files/6845003/PIR_github.issue.docx)

**Comment by Srisatya912** [comment]
hi sir. I'm ready to demonstrate.
