### ISSUE TITLE
Real Time Operation

### ISSUE THREAD

**Issue by mikeshams** [nireehasharma/Capstone-Project_G3#9]
1. Demonstrate this task in an acceptable way like what G2 did!
2. Reflect your modified code and required explanation in your ppt file again!

**Comment by nireehasharma** [comment]
Greetings of the day Sir,

we have modified the code according to the requirements and updated it in the ppt file.

**Comment by nireehasharma** [comment]
Greetings Sir,

2.  Below attachment is the modified code. Slide 17,21, 22, 23, 24,29 are the Modified slides.  I have modified the main code by adding Priority Queue and will demonstrate the task in the class

[Fourth Individual Meeting- Real time Operation.pptx](https://github.com/nireehasharma/Capstone-Project_G3/files/6935810/Fourth.Individual.Meeting-.Real.time.Operation.pptx)
